# Generated by Django 6.0.4 on 2026-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrainScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=50, null=True)),
                ('original_image', models.ImageField(upload_to='scans/original/')),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='scans/heatmaps/')),
                ('segmentation_mask', models.ImageField(blank=True, null=True, upload_to='scans/masks/')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('prediction', models.CharField(choices=[('tumor', 'Tumor'), ('no_tumor', 'No Tumor'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('insight_text', models.TextField(default='Highlighted region indicates suspected tumor area.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
