# Generated by Django 6.0.4 on 2026-04-13 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainscan',
            name='original_image',
        ),
        migrations.AddField(
            model_name='brainscan',
            name='scan_file',
            field=models.FileField(blank=True, null=True, upload_to='scans/original/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'dcm'])]),
        ),
    ]
