# Generated by Django 6.0.4 on 2026-04-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_remove_brainscan_original_image_brainscan_scan_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainscan',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
