# Generated by Django 6.0.4 on 2026-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_brainscan_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainscan',
            name='mask_area_pixels',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainscan',
            name='mask_area_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainscan',
            name='max_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainscan',
            name='mean_mask_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brainscan',
            name='validation_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brainscan',
            name='insight_text',
            field=models.TextField(default='Awaiting analysis.'),
        ),
        migrations.AlterField(
            model_name='brainscan',
            name='prediction',
            field=models.CharField(choices=[('tumor_suspected', 'Tumor Suspected'), ('no_tumor', 'No Tumor'), ('invalid_input', 'Invalid Input'), ('uncertain', 'Uncertain'), ('pending', 'Pending')], default='pending', max_length=30),
        ),
    ]
